### ISSUE TITLE
old version

### ISSUE THREAD

**Issue by zhengnx0906** [cambel/ur_openai_gym#1]
Sorry to bother you. You have changed the UR3 package in your warehouse. It seems that your project should be executed under the MTC branch, but now it has become the master branch, so I can't execute the project according to readme.

**Comment by cambel** [comment]
Hi @zhengnx0906,

Sorry for the late reply. 

I don't understand what you mean exactly. Are you trying to use moveit?

**Comment by zhengnx0906** [comment]
Sorry to bother you.Your readme has been updated, so this issue has been resolved. Thank you.

---Original---
From: ***@***.***&gt;
Date: Tue, May 3, 2022 19:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cambel/ur_openai_gym] old version (Issue #1)




 
Hi @zhengnx0906,
 
Sorry for the late reply.
 
I don't understand what you mean exactly. Are you trying to use moveit?
