### ISSUE TITLE
Missing ur3 dependencies in Docker installation

### ISSUE THREAD

**Issue by ACTP0H0M** [cambel/ur_openai_gym#2]
Hello,

to install ur_openai_gym we used `RUN-DOCKER.sh`, however there are some issues with the Dockerfile.

There is a block in Dockerfile:
```
# Installing repo required for homework
RUN /bin/bash -c "cd ~/ros_ws/src \
    && git clone https://***@github.com/cambel/ros-universal-robots.git trufus"
```

There is no such repository as far as we can tell, so we tried replacing this instruction by

```
RUN /bin/bash -c "cd ~/ros_ws/src \
    && git clone https://github.com/cambel/ur3.git trufus"
```

Unfortunately, after the `docker-compose` contained in `RUN-DOCKER.sh` our `trufus` directory looks like this:

```
root@localhost:~/ros_ws/src/trufus# ls
LICENSE  README.md  RUN-DOCKER.sh  dependencies.rosinstall  docker  ur_openai  ur_rl
```

There, `dependencies.rosinstall` look like this:
```
- git:
    local-name: ros_ur3
    uri: https://github.com/cambel/ur3.git
    version: master

```
Nevertheless, after complete `RUN-DOCKER.sh` there are no ur3 or ur related packages seen under `rospack list`.

May we request that you update the Docker installation instructions for `ur_openai_gym` so that we have complete dependencies?

**Comment by cambel** [comment]
Hi @ACTP0H0M,

Sorry, this repo has been broken for a while now. 
I just updated it.
Please try building the docker container again with the latest version of the code.

**Comment by ACTP0H0M** [comment]
Hi @cambel !
Thank you for the quick response, we were able to run the environment with 3 cubes after your update. I have yet another question, will open a new issue for that.
Cheers
