### ISSUE TITLE
Running the peg-in-hole environment

### ISSUE THREAD

**Issue by ACTP0H0M** [cambel/ur_openai_gym#3]
Hi again @cambel !

We are researching peg-in-hole assembly and would like to learn from your code. We will cite you if we can apply your approach to our scenario. However, when trying to run the environment demonstrated in your paper and on the GIF:
 ```
roslaunch ur3_gazebo ur3e_dual.launch peg_shape:=cube
 ```
we get a missing launch file error:
```
RLException: [ur3e_dual.launch] is neither a launch file in package [ur3_gazebo] nor is [ur3_gazebo] a launch file name
```
It seems that the `ur3e_gazebo` package is missing. Also we ask ourselves whether it is `ur3e_dual.launch` that needs to be started.

We would really like to test out your development and would appreciate if you included the missing dependencies for the scenario from your paper and maybe update the README.

Regards from Germany

**Comment by cambel** [comment]
Hi @ACTP0H0M,

Thank you for your interest in my repository. If you are interested in the peg-in-hole (PIH) assembly, I recommend you also check my latest [repository](https://github.com/cambel/robot-learning-cl-dr) where the PIH is the target task. This repository is just to illustrate the method used to train a Reinforcement Learning agent using Gazebo/ROS, but only contains simple environments for reaching tasks in joint space or Cartesian space.

Please ignore the README, it contains outdated instructions that are actually not part of this repository.

**Comment by ACTP0H0M** [comment]
Thank you for the swift reply, the new repository works properly!
